# Generated by Django 3.1.2 on 2020-10-17 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='Enter a make (eg:toyota)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')]),
        ),
    ]
