# Generated by Django 3.1.2 on 2020-10-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many', '0002_auto_20201020_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
