# Generated by Django 3.1.2 on 2020-10-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('many', '0003_auto_20201020_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[('LEARNER', 'LEARNER'), ('IA', 'Instructional Assistant'), ('GSI', 'Grad Student Instructor'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Administrator')], default='LEARNER')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='many.course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='many.person')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(through='many.Membership', to='many.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='courses',
            field=models.ManyToManyField(through='many.Membership', to='many.Course'),
        ),
    ]
