# Generated by Django 3.1.2 on 2020-10-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many', '0004_auto_20201020_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.TextField(choices=[('LEARNER', 'LEARNER'), ('IA', 'Instructional Assistant'), ('GSI', 'Grad Student Instructor'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Administrator')], default='LEARNER'),
        ),
    ]
