# Generated by Django 3.1.2 on 2020-10-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many', '0007_auto_20201020_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.TextField(choices=[(1, 'LEARNER'), (1000, 'Instructional Assistant'), (2000, 'Grad Student Instructor'), (5000, 'Instructor'), (10000, 'Administrator')], default='LEARNER'),
        ),
    ]
